ESTILO_MAIN_WINDOW={"background":"#F7E4C0","border":1,"borderwidth":2,"relief":"sunken"}
FAMILY_FONT_NOTIFICATIONS="D:\\proyectos\\proyectX\\multitool_V2\\ui\\assets\\fonts\\Bitcount_Grid_Single\\static\\BitcountGridSingle_Roman-Bold.ttf"
#*-----------------------------LABELS---------------------------------------
LABEL_PATHS_STYLE={"background":"#ffffff","foreground":"#000000","border":"1","borderwidth":2,"relief":"raised","font":("Century",10)}
LABEL_NOTIFICATION_VALID={"activeforeground":"#257B0A","font":("BitcountGridSingle_Roman",10),"state":"active","justify":"center","relief":"capas","compound":"bottom"}
LABEL_NOTIFICATION_INVALID={"activeforeground":"#AB1A00","font":("BitcountGridSingle_Roman",16),"state":"active","height":3,"justify":"center","relief":"capas","compound":"bottom"}
LABEL_NOTIFICATION_ALERT={"activeforeground":"#c9c03a","font":("BitcountGridSingle_Roman",13),"state":"active","height":6,"justify":"center","relief":"capas","compound":"bottom"}
#*----------------------------FRAMES----------------------------------------
FRAME_NOTIFICATION_STANDARD={"background":"#FFFFFF"}
FRAME_NOTIFICATION_VALID={"highlightcolor":"#2BB700","highlighttickness":2,"bd":1,"border":1,"relief":"raised"}
FRAME_NOTIFICATION_INVALID={"highlightcolor":"#FF2600","highlighttickness":8,"bd":1,"border":1,"borderwidth":3,"relief":"sunken"}
FRAME_NOTIFICATION_ALERT={"highlightcolor":"#ffee00","highlighttickness":5,"bd":1,"border":1,"borderwidth":6,"relief":"groove"}
LABEL_IMAGE_NOTIFICATION={"background":"#ffffff","anchor":"center"}
